language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.4.1
  - ruby-head

matrix:
  include:
    - rvm: rbx-4
      dist: trusty
      name: Rubinius
  allow_failures:
    - rvm: ruby-head
    - name: Rubinius
